import OpenAI from 'openai';
import { ENV } from '../../config/env.js';

const client = new OpenAI({ apiKey: ENV.openAiApiKey || undefined });

export async function generateReply(prompt) {
  if (!prompt || typeof prompt !== 'string') {
    throw new Error('Prompt must be a non-empty string');
  }

  if (!ENV.openAiApiKey) {
    throw new Error('OpenAI API key is not configured');
  }

  const response = await client.chat.completions.create({
    model: 'gpt-5',
    messages: [{ role: 'user', content: prompt }]
  });

  const message = response?.choices?.[0]?.message?.content;

  if (!message) {
    throw new Error('No reply generated by GPT');
  }

  return message.trim();
}
